# This is a basic workflow that is manually triggered

name: Workflow de configuración de entornos

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: '¿Quién eres, notas?'
        # Default value if no value is explicitly provided
        default: 'Amo'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
        
      entorno:
        description: '¿A qué entorno vas a aplicar realizar el desarrollo?'
        default: 'prod'
        required: true
        type: string
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Saluditos:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Saludo
      run: echo "Hello ${{ inputs.name }}"
    - name: Entorno
      run: mkdir -p /home/tesoro; cd /home/tesoro; echo "Desarrollo a ${{ inputs.entorno }} realizado correctamente por ${{ inputs.name }} el `date +'%d/%m/%Y %H:%M:%S'`" >> execution_log.log; cat execution_log.log
